"""S26: Pull-request generator for passing migration tracks.

For each repo that achieved minimal=True, generates a PR body (with the
migration diff, pass/fail summary, and CI badge) and optionally opens a
real GitHub PR via the GH CLI or API.

The three concrete deliverables:
  1. pr_body(result, diff_text) → formatted markdown string
  2. collect_passing(results_path)  → list of (repo, track, diff_path)
  3. open_pr(repo, track, branch, title, body, token) → PR URL (or dry-run)

The first two are fully testable offline. The third requires a GitHub token
and is guarded by dry_run=True by default.

CLI (dry run — prints PR bodies without posting):
    uv run python -m migration_agent.pr_generator --track T3 --dry-run

CLI (open real PRs on forks):
    uv run python -m migration_agent.pr_generator --track T3 --token $GH_TOKEN
"""

import json
import os
import subprocess
import urllib.parse
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LOGS_DIR = REPO_ROOT / "workdir" / "_logs"
TRAJ_BASE = REPO_ROOT / "workdir" / "trajectories"

_PAPER_URL = "https://arxiv.org/abs/2505.09569"
_PROJECT_URL = "https://github.com/syedk04/java-migration-bench"

# Maximum diff lines to inline in PR body — long diffs are linked, not inlined.
_MAX_DIFF_LINES = 200


def pr_body(
    repo: str,
    track: str,
    base_commit: str,
    diff_text: str,
    minimal: bool,
    maximal: bool,
    calls_used: int,
    maximal_detail: str = "",
) -> str:
    """Render a GitHub PR body for a passing migration.

    The body explains what changed, which checker gates it passed,
    and links back to the benchmark project.
    """
    diff_lines = diff_text.splitlines()
    if len(diff_lines) <= _MAX_DIFF_LINES:
        diff_block = "```diff\n" + diff_text.rstrip() + "\n```"
    else:
        # Inline only the first 100 lines and note truncation.
        preview = "\n".join(diff_lines[:100])
        diff_block = (
            f"```diff\n{preview}\n```\n\n"
            f"*(diff truncated — {len(diff_lines)} lines total)*"
        )

    gates = []
    gates.append("- [x] r1: `mvn clean verify` green under Java 17")
    gates.append("- [x] r2: compiled bytecode is major version 61 (Java 17)")
    gates.append("- [x] r3: test bodies unchanged (tamper gate)")
    gates.append("- [x] r4: test count non-decreasing")
    if maximal:
        gates.append(f"- [x] r5: all deps at latest major version ({maximal_detail or 'maximal'})")
    else:
        gates.append(f"- [ ] r5: deps not fully updated ({maximal_detail or 'not checked'})")

    gates_str = "\n".join(gates)

    calls_line = f"{calls_used} LLM calls" if calls_used else "static tool (no LLM calls)"

    return f"""\
## Java 8 → 17 migration ({track})

Automated migration of `{repo}` from Java 8 to Java 17, generated by the
[java-migration-bench]({_PROJECT_URL}) reproducibility project
([MigrationBench paper]({_PAPER_URL})).

**Base commit:** `{base_commit}`
**Track:** `{track}` · **Cost:** {calls_line}

### Checker gates passed

{gates_str}

### Migration diff

{diff_block}

---
*Generated by [java-migration-bench]({_PROJECT_URL}) — \
reproducing MigrationBench on free-tier infrastructure.*
"""


def collect_passing(results_path: Path, track: str) -> list[dict]:
    """Return records from a results JSON where minimal=True.

    Each record is augmented with a 'diff_path' pointing to the stored
    git diff in workdir/trajectories/<track>/<safe_repo>/migration.diff
    (written by agent_loop if it ran; may not exist for static tracks).
    """
    if not results_path.exists():
        return []
    records = json.loads(results_path.read_text())
    passing = []
    for r in records:
        if not r.get("minimal"):
            continue
        repo = r["repo"]
        safe = repo.replace("/", "__")
        # agent_loop saves diff at <traj_dir>/<safe>.diff (parallel to .jsonl)
        diff_path = TRAJ_BASE / track.lower() / f"{safe}.diff"
        passing.append({**r, "diff_path": str(diff_path)})
    return passing


def _read_diff(diff_path: str) -> str:
    """Read migration diff from trajectory, or fall back to git diff."""
    p = Path(diff_path)
    if p.exists():
        return p.read_text(encoding="utf-8", errors="replace")

    # Fall back: regenerate from cloned workdir if available.
    repo = Path(diff_path).parent.name.replace("__", "/")
    safe = repo.replace("/", "__")
    repo_dir = REPO_ROOT / "workdir" / safe
    if repo_dir.is_dir():
        try:
            result = subprocess.run(
                ["git", "diff", "HEAD~1", "HEAD"],
                cwd=repo_dir,
                capture_output=True,
                text=True,
                timeout=30,
            )
            return result.stdout
        except Exception:  # noqa: BLE001
            pass
    return "(diff not available)"


def _gh_fork_and_pr(
    repo: str,
    branch: str,
    title: str,
    body: str,
    token: str,
    base_branch: str = "main",
) -> str:
    """Fork repo and open a PR via GitHub REST API.

    Returns the PR URL on success, raises on failure.
    Does NOT push any code — assumes the diff has already been applied
    to a branch on the fork. This is a post-migration step only.
    """
    owner, name = repo.split("/", 1)
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
    }

    # Step 1: fork (idempotent — GitHub returns existing fork if present).
    fork_url = f"https://api.github.com/repos/{owner}/{name}/forks"
    fork_data = json.dumps({}).encode()
    req = urllib.request.Request(fork_url, data=fork_data, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=30) as resp:
        fork = json.loads(resp.read())
    fork_full_name = fork["full_name"]  # e.g. syedk04/repo-name

    # Step 2: open PR from fork branch into upstream default branch.
    pr_url = f"https://api.github.com/repos/{owner}/{name}/pulls"
    pr_data = json.dumps({
        "title": title,
        "body": body,
        "head": f"{fork_full_name.split('/')[0]}:{branch}",
        "base": base_branch,
    }).encode()
    req = urllib.request.Request(pr_url, data=pr_data, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=30) as resp:
        pr = json.loads(resp.read())
    return pr["html_url"]


def main() -> None:
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="S26: PR generator for passing migrations.")
    parser.add_argument("--track", required=True, choices=["T2", "T3", "T4", "T3-lite", "T4-lite"])
    parser.add_argument("--dry-run", action="store_true", default=True,
                        help="Print PR bodies without posting (default: True).")
    parser.add_argument("--post", action="store_true",
                        help="Actually post PRs (requires --token).")
    parser.add_argument("--token", default=None,
                        help="GitHub token (or set GH_TOKEN env var).")
    parser.add_argument("--max-prs", type=int, default=3,
                        help="Maximum PRs to open (default: 3).")
    args = parser.parse_args()

    dry_run = not args.post
    token = args.token or os.environ.get("GH_TOKEN")
    if args.post and not token:
        print("ERROR: --post requires --token or GH_TOKEN env var.", file=sys.stderr)
        sys.exit(1)

    results_path = LOGS_DIR / f"{args.track.lower()}_reporting_50.json"
    passing = collect_passing(results_path, args.track)

    if not passing:
        print(f"No passing results found for {args.track} in {results_path}")
        return

    print(f"Found {len(passing)} passing repos for {args.track}")
    printed = 0
    for r in passing[:args.max_prs]:
        repo = r["repo"]
        diff_text = _read_diff(r["diff_path"])
        body = pr_body(
            repo=repo,
            track=args.track,
            base_commit=r.get("base_commit", "unknown"),
            diff_text=diff_text,
            minimal=r.get("minimal", False),
            maximal=r.get("maximal", False),
            calls_used=r.get("calls_used", 0),
            maximal_detail=r.get("maximal_detail", ""),
        )
        title = f"Java 8→17 migration ({args.track})"

        if dry_run:
            print(f"\n{'='*60}")
            print(f"DRY RUN — {repo}")
            print(f"Title: {title}")
            print("Body preview (first 500 chars):")
            print(body[:500])
            print("...")
        else:
            branch = f"java17-migration-{args.track.lower()}"
            try:
                url = _gh_fork_and_pr(repo, branch, title, body, token)  # type: ignore[arg-type]
                print(f"PR opened: {url}")
                printed += 1
            except Exception as e:  # noqa: BLE001
                print(f"ERROR opening PR for {repo}: {e}", file=sys.stderr)

    if not dry_run:
        print(f"\nOpened {printed}/{min(len(passing), args.max_prs)} PRs.")
    else:
        print("\nDry run complete. Pass --post --token $GH_TOKEN to open real PRs.")


if __name__ == "__main__":
    main()
